restoring build artifacts in assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -10,18 +10,20 @@ function rvm_use() {
   fi
 }
 
-if [ "$RUBY_VERSION" != "" ]; then
-  echo "Using ruby from RUBY_VERSION environment variable"
-  rvm_use $RUBY_VERSION
-elif [ -f Gemfile ]; then
-  echo "Using ruby from Gemfile"
-  line=`grep -e '^ruby ' Gemfile`
-  if [ $? -eq 0 ]; then
-    ruby_version=`echo $line | sed "s/ruby *'\(.*\)'/\1/"`
-    echo "Found ruby version: $ruby_version"
-    rvm_use $ruby_version
+function detect_ruby_version() {
+  if [ "$RUBY_VERSION" != "" ]; then
+    echo "Using ruby from RUBY_VERSION environment variable"
+    rvm_use $RUBY_VERSION
+  elif [ -f Gemfile ]; then
+    echo "Using ruby from Gemfile"
+    line=`grep -e '^ruby ' Gemfile`
+    if [ $? -eq 0 ]; then
+      ruby_version=`echo $line | sed "s/ruby *'\(.*\)'/\1/"`
+      echo "Found ruby version: $ruby_version"
+      rvm_use $ruby_version
+    fi
   fi
-fi
+}
 
 function rake_assets_precompile() {
   [[ "$DISABLE_ASSET_COMPILATION" == "true" ]] && return
@@ -35,18 +37,30 @@ function rake_assets_precompile() {
   bundle exec rake assets:precompile
 }
 
+detect_ruby_version
+
+# exit immediately on error
 set -e
 
+# set environment
 export RACK_ENV=${RACK_ENV:-"production"}
 
+# restore build artifacts
+if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
+  mv /tmp/artifacts/* $HOME/.
+fi
+
+# rubygem mirror
 if [ -n "$RUBYGEM_MIRROR" ]; then
   bundle config mirror.https://rubygems.org $RUBYGEM_MIRROR
 fi
 
+# copy source
 shopt -s dotglob
 echo "---> Installing application source ..."
 mv /tmp/src/* ./
 
+# build source
 echo "---> Building your Ruby application from source ..."
 if [ -f Gemfile ]; then
   ADDTL_BUNDLE_ARGS=""
